apiVersion: v1
kind: Service
metadata:
  name: {{ include "laki.backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "laki.backend.labels" . | nindent 4 }}
  {{- $annotations := merge (dict) .Values.backend.service.annotations .Values.commonAnnotations }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - name: http
      port: {{ .Values.backend.service.httpPort }}
      targetPort: http
      protocol: TCP
      {{- if and (eq .Values.backend.service.type "NodePort") .Values.backend.service.httpNodePort }}
      nodePort: {{ .Values.backend.service.httpNodePort }}
      {{- end }}
    - name: grpc
      port: {{ .Values.backend.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      {{- if and (eq .Values.backend.service.type "NodePort") .Values.backend.service.grpcNodePort }}
      nodePort: {{ .Values.backend.service.grpcNodePort }}
      {{- end }}
    {{- with .Values.backend.service.extraPorts }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  selector:
    {{- include "laki.backend.selectorLabels" . | nindent 4 }}
