apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laki.backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "laki.backend.labels" . | nindent 4 }}
  {{- with (include "laki.commonAnnotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicaCount }}
  {{- end }}
  {{- with .Values.backend.updateStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "laki.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "laki.backend.selectorLabels" . | nindent 8 }}
        {{- with .Values.backend.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.commonLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if include "laki.secret.enabled" . }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.backend.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.commonAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "laki.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "laki.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      {{- with .Values.backend.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.backend.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.backend.terminationGracePeriodSeconds }}
      {{- with .Values.backend.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: laki
          image: {{ include "laki.image" (dict "image" .Values.backend.image "context" $) }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          {{- with .Values.backend.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.containerPort }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.backend.grpcContainerPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "laki.configMapName" . }}
            {{- with .Values.backend.extraEnvFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            {{- include "laki.backend.secretEnv" . | nindent 12 }}
            {{- with .Values.backend.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if .Values.backend.customStartupProbe }}
          startupProbe:
            {{- toYaml .Values.backend.customStartupProbe | nindent 12 }}
          {{- else if .Values.backend.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: {{ .Values.backend.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.backend.startupProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.backend.startupProbe.failureThreshold }}
            successThreshold: {{ .Values.backend.startupProbe.successThreshold }}
          {{- end }}
          {{- if .Values.backend.customLivenessProbe }}
          livenessProbe:
            {{- toYaml .Values.backend.customLivenessProbe | nindent 12 }}
          {{- else if .Values.backend.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: {{ .Values.backend.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.backend.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.backend.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.backend.livenessProbe.successThreshold }}
          {{- end }}
          {{- if .Values.backend.customReadinessProbe }}
          readinessProbe:
            {{- toYaml .Values.backend.customReadinessProbe | nindent 12 }}
          {{- else if .Values.backend.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: {{ .Values.backend.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.backend.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.backend.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.backend.readinessProbe.successThreshold }}
          {{- end }}
          {{- with .Values.backend.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.backend.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- with .Values.backend.sidecars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.backend.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
