{{- if .Values.backend.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "laki.backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "laki.backend.labels" . | nindent 4 }}
  {{- with (include "laki.commonAnnotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.backend.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.backend.podDisruptionBudget.maxUnavailable }}
  {{- else }}
  minAvailable: {{ .Values.backend.podDisruptionBudget.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "laki.backend.selectorLabels" . | nindent 6 }}
{{- end }}
{{- if and .Values.ui.enabled .Values.ui.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "laki.ui.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "laki.ui.labels" . | nindent 4 }}
  {{- with (include "laki.commonAnnotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ui.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.ui.podDisruptionBudget.maxUnavailable }}
  {{- else }}
  minAvailable: {{ .Values.ui.podDisruptionBudget.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "laki.ui.selectorLabels" . | nindent 6 }}
{{- end }}
