{{- if include "laki.secret.enabled" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "laki.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "laki.backend.labels" . | nindent 4 }}
  {{- $annotations := merge (dict) .Values.secret.annotations .Values.commonAnnotations }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- if and (not .Values.database.existingSecret) .Values.database.connectionString }}
  DB_CONN_STRING: {{ .Values.database.connectionString | quote }}
  {{- end }}
  {{- if and (not .Values.backend.webhookSecret.existingSecret) .Values.backend.webhookSecret.value }}
  WEBHOOK_SECRET: {{ .Values.backend.webhookSecret.value | quote }}
  {{- end }}
  {{- if and .Values.redis.enabled (not .Values.redis.existingSecret) .Values.redis.password }}
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
  {{- end }}
  {{- with .Values.providers.email.apiKey }}
  EMAIL_API_KEY: {{ . | quote }}
  {{- end }}
  {{- with .Values.providers.email.apiSecret }}
  EMAIL_API_SECRET: {{ . | quote }}
  {{- end }}
  {{- with .Values.providers.sms.twilio.authToken }}
  TWILIO_AUTH_TOKEN: {{ . | quote }}
  {{- end }}
  {{- with .Values.providers.sms.afro.token }}
  SMS_TOKEN: {{ . | quote }}
  {{- end }}
  {{- with .Values.providers.push.serverKey }}
  FCM_SERVER_KEY: {{ . | quote }}
  {{- end }}
{{- end }}
